#!/bin/bash
#
# Copyright (C) 2014 Wenva <lvyexuwenfa100@126.com>
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is furnished
# to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

set -e

spushd() {
     pushd "$1" 2>&1> /dev/null
}

spopd() {
     popd 2>&1> /dev/null
}

info() {
     local green="\033[1;32m"
     local normal="\033[0m"
     echo -e "[${green}INFO${normal}] $1"
}

cmdcheck() {
    command -v $1>/dev/null 2>&1 || { error >&2 "Please install command $1 first."; exit 1; }   
}

error() {
     local red="\033[1;31m"
     local normal="\033[0m"
     echo -e "[${red}ERROR${normal}] $1"
}

curdir() {
    if [ ${0:0:1} = '/' ] || [ ${0:0:1} = '~' ]; then
        echo "$(dirname $0)"
    elif [ -L $0 ];then
        name=`readlink $0`
        echo $(dirname $name)
    else
        echo "`pwd`/$(dirname $0)"
    fi
}


#########################################
###           GROBLE DEFINE           ###
#########################################

VERSION=1.0.0
AUTHOR=smallmuou

#########################################
###             ARG PARSER            ###
#########################################

usage() {
cat << EOF
`basename $0` version $VERSION by $AUTHOR

USAGE: `basename $0` [OPTIONS] pcmfile

DESCRIPTION:

OPTIONS:
    -h                Show this help message and exit

EOF
exit 1
}

while getopts 'h' arg; do
    case $arg in
        h)
            usage
            ;;
        ?)
            usage
            ;;
    esac
done

shift $(($OPTIND - 1))

[ $# -ne 1 ] && usage

cmdcheck jshon

pcmfile=$1

[ ! -f $pcmfile ] && { error "input file $pcmfile does not exist."; exit -1; }

. /etc/sm.conf

[ -z "$BAIDU_YUYIN_API_KEY" ] && { error 'Please config BAIDU_YUYIN_API_KEY in /etc/sm.conf.'; exit -1; }
[ -z "$BAIDU_YUYIN_SECRET_KEY" ] && { error 'Please config BAIDU_YUYIN_SECRET_KEY in /etc/sm.conf.'; exit -1; }
[ -z "$BAIDU_YUYIN_CUID" ] && { error 'Please config BAIDU_YUYIN_CUID in /etc/sm.conf.'; exit -1; }

#########################################
###            MAIN ENTRY             ###
#########################################

#!/bin/bash

access_token=`curl -s "https://openapi.baidu.com/oauth/2.0/token?grant_type=client_credentials&client_id=$BAIDU_YUYIN_API_KEY&client_secret=$BAIDU_YUYIN_SECRET_KEY"|jshon -e access_token|sed 's/"//g'`
size=`/bin/ls -l $pcmfile|awk '{print $5}'`
base64data=`base64 $pcmfile`

body="{
    \"format\":\"pcm\",
    \"rate\":8000,
    \"channel\":1,
    \"token\":\"$access_token\",
    \"cuid\":\"$BAIDU_YUYIN_CUID\",
    \"len\":$size,
    \"speech\":\"$base64data\"
}"

result=`curl -s -H "Content-Type:application/json" --data "$body" "http://vop.baidu.com/server_api"`
if [ `echo $result|jshon -e err_no` -eq 0 ];then
    echo $result|jshon -e result
else
    error "fail. the result is $result"
fi
